#!/usr/bin/env bash
#Change your home IP

sudo sed -i 's/^127\.0\.0\.2.*$/127.0.0.1 \tlocalhost/' /etc/hosts
sudo sed -i '/^8\.8\.8\.8/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null