#!/usr/bin/env bash
#Change your home IP
echo "127.0.0.2 localhost" > /etc/hosts
sudo sed -i 's/^127\.0\.0\.1.*$/127.0.0.2 \tlocalhost/' /etc/hosts
sudo sed -i '/^8\.8\.8\.8/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null